INSERT INTO NODE 
(NODE_ID, NODE_NAME, DESCRIPTION, MENU, NODE_TYPE, PARENT_NODE_GROUP_NAME, PARENT_NODE_GROUP_ID, PARENT_NODE) 
VALUES
(100, 'NODE_ID', 'Sample Text', 'Sample Text', 'Transponder', 'Product Node Group Name', 200, 300);